export function credentialPortalDocument(): string {
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>Andory Bot 凭据</title>
  <style>
    :root{font-family:"Noto Sans CJK SC","Source Han Sans SC",system-ui,sans-serif;color:#283142;background:#eef2f8;accent-color:#477de8;--ink:#283142;--muted:#747e90;--line:#d7deea;--paper:#fff;--blue:#477de8;--blue-dark:#315fbf;--danger:#cf5265}
    *{box-sizing:border-box}html{min-height:100%;background:linear-gradient(150deg,#f8faff 0,#edf2fb 48%,#e6edf8 100%)}body{margin:0;min-height:100vh;background:transparent}
    ::selection{background:#b9cffb;color:#17233a}button,input{font:inherit}button:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid #9dbcf7;outline-offset:2px}
    .shell{width:min(1040px,calc(100% - 32px));margin:0 auto;padding:46px 0 64px}.mast{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:22px}.brand{font-size:30px;font-weight:900;letter-spacing:-.03em}.brand span{color:var(--blue)}.lede{max-width:620px;margin:8px 0 0;color:var(--muted);line-height:1.7}.statusline{font-size:13px;font-weight:800;color:#5d6880;padding:8px 0}
    .panel{background:var(--paper);border:1px solid var(--line);border-radius:18px;box-shadow:0 18px 48px #3a4d7415;overflow:hidden}.auth{width:min(520px,100%);margin:54px auto}.tabs{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--line)}.tab{border:0;background:#f7f9fc;color:#687286;padding:15px;cursor:pointer;font-weight:800}.tab.active{background:#fff;color:var(--blue);box-shadow:inset 0 -3px var(--blue)}.form{padding:28px;display:grid;gap:17px}.field{display:grid;gap:7px}.field span{font-size:13px;font-weight:800;color:#5e687b}.field input{width:100%;border:1px solid #cbd4e2;border-radius:10px;padding:12px 13px;color:var(--ink);background:#fbfcfe}.field input::placeholder{color:#8b94a3}.hint{color:var(--muted);font-size:13px;line-height:1.6}
    .button{border:0;border-radius:10px;padding:11px 17px;font-weight:850;cursor:pointer;background:var(--blue);color:#fff;box-shadow:0 7px 18px #477de82e;transition:background .16s ease,transform .16s ease}.button:hover{background:var(--blue-dark);transform:translateY(-1px)}.button:disabled{opacity:.5;cursor:wait;transform:none}.button.secondary{background:#edf2fb;color:#365caa;box-shadow:none}.button.danger{background:#fff0f2;color:#b93f53;box-shadow:none}.button.slim{padding:8px 12px;font-size:13px}.message{min-height:22px;color:#b13f52;font-size:14px;line-height:1.5}.message.ok{color:#28745a}
    .mfa{width:min(580px,100%);margin:42px auto;padding:28px}.mfa h1{margin:0 0 9px;font-size:25px}.mfa>p{margin:0 0 20px;color:var(--muted);line-height:1.65}.setup{padding:16px;border:1px solid #b8caee;border-radius:12px;background:#f4f7fe;margin-bottom:18px}.setup strong{display:block;margin-bottom:8px}.setup code{display:block;padding:10px;border-radius:8px;background:#202a3a;color:#fff;overflow-wrap:anywhere;font:600 13px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.setup p{margin:9px 0 0;color:#67738a;font-size:13px;line-height:1.55}.otpform{display:grid;grid-template-columns:1fr auto;gap:10px}.otpform input{border:1px solid #cbd4e2;border-radius:10px;padding:12px 13px;font-size:20px;font-weight:850;letter-spacing:.18em;font-variant-numeric:tabular-nums;min-width:0}.mfalinks{display:flex;justify-content:space-between;align-items:center;margin-top:12px}
    .dashboard{display:grid;gap:18px}.accountbar{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:22px 24px}.identity{min-width:0}.email{font-size:20px;font-weight:900;overflow-wrap:anywhere}.role{display:inline-flex;margin-top:7px;padding:5px 10px;border-radius:999px;background:#edf3ff;color:#406fc9;font-size:12px;font-weight:900}.role.admin{background:#f5eefe;color:#8254b7}.actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
    .workspace{display:grid;grid-template-columns:minmax(250px,.75fr) minmax(0,1.6fr);min-height:480px}.rail{padding:24px;border-right:1px solid var(--line);background:#fafbfd}.rail h2,.content h2{font-size:18px;margin:0 0 9px}.rail p,.content .intro{margin:0 0 20px;color:var(--muted);font-size:14px;line-height:1.65}.scope{display:grid;gap:9px;margin-bottom:22px}.scope button{text-align:left;border:1px solid var(--line);border-radius:11px;background:#fff;padding:13px;cursor:pointer;color:var(--ink)}.scope button strong{display:block;margin-bottom:4px}.scope button span{color:var(--muted);font-size:12px}.scope button.active{border-color:#8eacf0;background:#f2f6ff;box-shadow:0 0 0 2px #dce7ff inset}.scope button[hidden]{display:none}
    .content{padding:25px 27px}.createbar{display:grid;grid-template-columns:1fr auto;gap:10px;padding-bottom:22px;border-bottom:1px solid var(--line)}.createbar input{border:1px solid #cbd4e2;border-radius:10px;padding:11px 12px;min-width:0}.credentials{display:grid;gap:10px;margin-top:18px}.credential{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;padding:14px 15px;border:1px solid var(--line);border-radius:12px;background:#fff}.credential strong{display:block;margin-bottom:5px}.meta{color:var(--muted);font-size:12px;font-variant-numeric:tabular-nums}.empty{padding:38px 20px;text-align:center;color:var(--muted);border:1px dashed #c8d2e2;border-radius:12px;background:#fbfcfe}
    .reveal{margin-top:18px;padding:18px;border:1px solid #a9c0ef;border-radius:13px;background:#f3f7ff}.reveal h3{margin:0 0 8px;font-size:16px}.reveal p{margin:0 0 12px;color:#65718a;font-size:13px}.secret{display:grid;grid-template-columns:1fr auto;gap:9px}.secret code{display:block;min-width:0;padding:11px 12px;border-radius:9px;background:#202a3a;color:#f5f7fb;overflow-wrap:anywhere;font:600 13px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}
    .bootstrap{margin-top:18px;padding:20px 24px}.bootstrap h2{margin:0 0 7px;font-size:17px}.bootstrap p{margin:0 0 13px;color:var(--muted);font-size:13px;line-height:1.6}.bootstrapform{display:grid;grid-template-columns:1fr auto;gap:9px}.bootstrap input{border:1px solid #cbd4e2;border-radius:10px;padding:11px 12px;min-width:0}
    footer{display:flex;justify-content:space-between;gap:18px;margin-top:18px;color:#7b8597;font-size:12px;line-height:1.6}.hidden{display:none!important}
    @media(max-width:760px){.shell{padding-top:26px}.mast{display:block}.statusline{margin-top:10px}.workspace{grid-template-columns:1fr}.rail{border-right:0;border-bottom:1px solid var(--line)}.scope{grid-template-columns:1fr 1fr}.accountbar{align-items:flex-start;flex-direction:column}.actions{justify-content:flex-start}.createbar,.bootstrapform{grid-template-columns:1fr}.credential{grid-template-columns:1fr}.credential .button{justify-self:start}.secret{grid-template-columns:1fr}.secret .button{justify-self:start}footer{display:block}.auth{margin-top:28px}}
  </style>
</head>
<body><main class="shell">
  <header class="mast"><div><div class="brand">Andory <span>Connector</span></div><p class="lede">为本地 OneBot 连接器签发独立凭据。凭据只在创建时显示一次；服务端仅保存不可逆哈希。</p></div><div class="statusline">holo.rettheory.top</div></header>

  <section id="auth" class="panel auth">
    <div class="tabs"><button class="tab active" data-mode="login">登录</button><button class="tab" data-mode="register">邮箱注册</button></div>
    <form id="authForm" class="form">
      <label class="field"><span>邮箱</span><input id="email" name="email" type="email" maxlength="254" autocomplete="email" required placeholder="you@example.com"></label>
      <label class="field"><span>密码</span><input id="password" name="password" type="password" minlength="10" maxlength="128" autocomplete="current-password" required placeholder="至少 10 个字符"></label>
      <div id="authHint" class="hint">使用已注册邮箱登录。</div>
      <button id="authSubmit" class="button" type="submit">登录</button><div id="authMessage" class="message" role="status"></div>
    </form>
  </section>

  <section id="mfa" class="panel mfa hidden">
    <h1>Authenticator 验证</h1><p>管理员操作需要 6 位动态验证码。验证码不会写入浏览器存储。</p>
    <div id="totpSetup" class="setup hidden"><strong>先在 Authenticator 中添加账户</strong><code id="totpSecret"></code><p>选择“输入设置密钥”，账户名填写 Andory。请在验证前妥善保存此密钥；页面关闭后不再显示。</p></div>
    <div class="otpform"><input id="totpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" placeholder="000000"><button id="verifyTotp" class="button">验证并继续</button></div>
    <div id="mfaMessage" class="message" role="status"></div><div class="mfalinks"><span class="hint">允许约 30 秒时钟误差</span><button id="cancelMfa" class="button secondary slim">退出登录</button></div>
  </section>

  <section id="dashboard" class="dashboard hidden">
    <div class="panel accountbar"><div class="identity"><div id="accountEmail" class="email"></div><span id="accountRole" class="role"></span></div><div class="actions"><a id="auditLink" class="button secondary slim hidden" href="/audit">别名审核</a><button id="logout" class="button secondary slim">退出登录</button></div></div>
    <div class="panel workspace">
      <aside class="rail"><h2>凭据类型</h2><p>不同类型拥有严格隔离的权限。普通账号只能创建 Bot 凭据。</p><div class="scope"><button class="active" data-scope="bot"><strong>Bot credential</strong><span>连接 OneBot 与普通 API</span></button><button id="auditScope" data-scope="audit" hidden><strong>Audit credential</strong><span>管理员审核接口</span></button></div><p>系统数据端使用单独部署 Secret，不会从此处签发。</p></aside>
      <section class="content"><h2 id="scopeTitle">Bot credentials</h2><p id="scopeIntro" class="intro">用于 Andory Connector。每个账号最多保留 5 个有效凭据。</p><div class="createbar"><input id="credentialLabel" maxlength="40" placeholder="名称，例如：家中 Bot"><button id="createCredential" class="button">生成 credential</button></div><div id="reveal" class="reveal hidden"><h3>立即复制</h3><p>关闭或刷新后无法再次查看完整值；遗失时请撤销并重新生成。</p><div class="secret"><code id="credentialValue"></code><button id="copyCredential" class="button secondary slim">复制</button></div></div><div id="credentialMessage" class="message" role="status"></div><div id="credentials" class="credentials"></div></section>
    </div>
    <section id="bootstrap" class="panel bootstrap hidden"><h2>激活首位管理员</h2><p>仅在系统还没有管理员时可用。输入部署者提供的一次性激活密钥；激活后此入口永久关闭。</p><div class="bootstrapform"><input id="bootstrapToken" type="password" autocomplete="off" placeholder="管理员激活密钥"><button id="bootstrapButton" class="button">激活管理员</button></div><div id="bootstrapMessage" class="message" role="status"></div></section>
  </section>
  <footer><span>Andory 与 Hololive 官方及 QualiArts 无关。</span><span>Credential 不写入浏览器存储。</span></footer>
</main>
<script>
const $=id=>document.getElementById(id);let mode='login',account=null,scope='bot',rows=[];
const auth=$('auth'),mfa=$('mfa'),dashboard=$('dashboard'),authForm=$('authForm'),authMessage=$('authMessage'),credentialMessage=$('credentialMessage');
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.mode)));
document.querySelectorAll('[data-scope]').forEach(button=>button.addEventListener('click',()=>setScope(button.dataset.scope)));
authForm.addEventListener('submit',submitAuth);$('logout').addEventListener('click',logout);$('cancelMfa').addEventListener('click',logout);$('verifyTotp').addEventListener('click',verifyTotp);$('totpCode').addEventListener('keydown',event=>{if(event.key==='Enter')verifyTotp()});$('createCredential').addEventListener('click',createCredential);$('copyCredential').addEventListener('click',copyCredential);$('bootstrapButton').addEventListener('click',bootstrapAdmin);
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data}
function setMode(next){mode=next;document.querySelectorAll('.tab').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));$('authSubmit').textContent=mode==='login'?'登录':'创建账号';$('authHint').textContent=mode==='login'?'使用已注册邮箱登录。':'注册后默认为普通用户，可立即生成 Bot credential。';$('password').autocomplete=mode==='login'?'current-password':'new-password';show(authMessage,'')}
async function submitAuth(event){event.preventDefault();const button=$('authSubmit');button.disabled=true;show(authMessage,'');try{const result=await api('/api/v1/auth/'+mode,{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});account=result.account;if(result.mfaRequired)showMfa(result.totpSetup);else await showDashboard()}catch(error){show(authMessage,error.message)}finally{button.disabled=false}}
async function restore(){try{const result=await api('/api/v1/auth/me');if(result.account){account=result.account;if(result.mfaRequired)showMfa();else await showDashboard()}}catch{}}
function showMfa(setup){auth.classList.add('hidden');dashboard.classList.add('hidden');mfa.classList.remove('hidden');$('totpCode').value='';show($('mfaMessage'),'');$('totpSetup').classList.toggle('hidden',!setup);$('totpSecret').textContent=setup?setup.secret:'';$('totpCode').focus()}
async function verifyTotp(){const button=$('verifyTotp');button.disabled=true;show($('mfaMessage'),'');try{const result=await api('/api/v1/auth/totp/verify',{method:'POST',body:JSON.stringify({code:$('totpCode').value})});account=result.account;$('totpSecret').textContent='';$('totpSetup').classList.add('hidden');await showDashboard()}catch(error){show($('mfaMessage'),error.message)}finally{button.disabled=false}}
async function showDashboard(){auth.classList.add('hidden');mfa.classList.add('hidden');dashboard.classList.remove('hidden');$('accountEmail').textContent=account.email;$('accountRole').textContent=account.role==='admin'?'管理员':'普通用户';$('accountRole').classList.toggle('admin',account.role==='admin');$('auditScope').hidden=account.role!=='admin';$('auditLink').classList.toggle('hidden',account.role!=='admin');$('bootstrap').classList.toggle('hidden',account.role==='admin');setScope(scope==='audit'&&account.role!=='admin'?'bot':scope);await loadCredentials()}
async function logout(){try{await api('/api/v1/auth/logout',{method:'POST',body:'{}'})}finally{location.reload()}}
function setScope(next){scope=next;document.querySelectorAll('[data-scope]').forEach(button=>button.classList.toggle('active',button.dataset.scope===scope));$('scopeTitle').textContent=scope==='audit'?'Audit credentials':'Bot credentials';$('scopeIntro').textContent=scope==='audit'?'仅管理员可签发，用于别名审核 API。':'用于 Andory Connector 与普通 API。每个账号最多保留 5 个有效凭据。';$('credentialLabel').placeholder=scope==='audit'?'名称，例如：审核台':'名称，例如：家中 Bot';$('reveal').classList.add('hidden');renderCredentials()}
async function loadCredentials(){const result=await api('/api/v1/credentials');rows=result.credentials||[];renderCredentials()}
function renderCredentials(){const host=$('credentials');host.replaceChildren();const visible=rows.filter(item=>item.scope===scope);if(!visible.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='暂无有效 credential';host.append(empty);return}for(const item of visible){const row=document.createElement('article');row.className='credential';const detail=document.createElement('div');const title=document.createElement('strong');title.textContent=item.label;const meta=document.createElement('div');meta.className='meta';meta.textContent='尾号 '+item.tokenHint+' · '+new Date(item.createdAt).toLocaleString();detail.append(title,meta);const revoke=document.createElement('button');revoke.className='button danger slim';revoke.textContent='撤销';revoke.addEventListener('click',()=>revokeCredential(item.id,revoke));row.append(detail,revoke);host.append(row)}}
async function createCredential(){const button=$('createCredential');button.disabled=true;show(credentialMessage,'');try{const result=await api('/api/v1/credentials',{method:'POST',body:JSON.stringify({scope,label:$('credentialLabel').value})});$('credentialValue').textContent=result.credential.value;$('reveal').classList.remove('hidden');$('credentialLabel').value='';rows.unshift(result.credential);renderCredentials();show(credentialMessage,'Credential 已生成，请立即复制。',true)}catch(error){show(credentialMessage,error.message)}finally{button.disabled=false}}
async function copyCredential(){const value=$('credentialValue').textContent;try{await navigator.clipboard.writeText(value);$('copyCredential').textContent='已复制';setTimeout(()=>$('copyCredential').textContent='复制',1600)}catch{show(credentialMessage,'浏览器拒绝复制，请手动选择 credential。')}}
async function revokeCredential(id,button){button.disabled=true;show(credentialMessage,'');try{await api('/api/v1/credentials/'+encodeURIComponent(id),{method:'DELETE',body:'{}'});rows=rows.filter(item=>item.id!==id);renderCredentials();show(credentialMessage,'Credential 已撤销。',true)}catch(error){show(credentialMessage,error.message);button.disabled=false}}
async function bootstrapAdmin(){const button=$('bootstrapButton');button.disabled=true;show($('bootstrapMessage'),'');try{const result=await api('/api/v1/auth/bootstrap-admin',{method:'POST',body:JSON.stringify({bootstrapToken:$('bootstrapToken').value})});account=result.account;$('bootstrapToken').value='';showMfa(result.totpSetup)}catch(error){show($('bootstrapMessage'),error.message)}finally{button.disabled=false}}
function show(node,text,ok=false){node.textContent=text;node.classList.toggle('ok',Boolean(ok))}
restore();
</script></body></html>`;
}
